name: Check Pull Request Labels

on: pull_request

jobs:
  check-pr-labels:
    name: 'Check Labels'
    runs-on:  ubuntu-latest 
    steps:
      - name: 'Check Labels'
        uses: actions/github-script@v6
        with:
          script: |
            const  labels = new Set( context.payload.pull_request.labels.map(x=>x.name) );
            if( !labels.has('My Label') ){
               core.setFailed('Did not find the label My Label on the pull request')
            }
      
        

    