name: CI

on: 
 push:
   branches: ["*"]

jobs:
  ci:
    name: 'CI'
    runs-on:  ubuntu-latest 
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Build'
        run: |
          echo "Starting Build"
          sleep 1
          echo "Build complete"

      - name: 'Run Tests'
        run: |
          echo "Tests complete"

          
  new_release:
    uses: ./.github/workflows/release.yml
    name: 'Create a new github release'
    needs: [ci]
    if: github.ref == 'refs/heads/main'
    
    

    