name: Testing

on: 
 push:
   branches: ["*"]

jobs:
  test:
    name: 'Testing'
    runs-on: [ self-hosted, ubuntu ]    
    steps:
      - name: 'Run Tests'
        run: |
          echo "Test have run"

    